# Site settings
name: Remix the Quarantine
email: cameron.buckley@thedeltaschool.org
url: https://www.thedeltaschool.org
description: "Sick Beats and Vids from Cool Kids"
author: "Quarantine Crew"
title: "Remix the Quarantine"
permalink: pretty
baseurl: /remixing-tds

# social
github:
  username: cameronbuckleyastate

twitter:
  username: username
